"""Database module for VAPT Scanner Pro."""
from .config import get_db_config
from .queries import (
    get_pool,
    get_connection,
    get_user_by_email,
    create_user,
    get_all_targets,
    get_target_by_id,
    get_target_by_url,
    get_or_create_target,
    update_target,
    delete_target,
    insert_scan_history,
    get_scan_history_for_target,
    insert_vulnerabilities,
    get_vulnerabilities,
    get_vulnerability_by_id,
    get_vulnerabilities_by_target_url,
    toggle_vulnerability_fixed,
    get_dashboard_stats,
    insert_report,
    get_reports,
    get_report_by_id,
    get_recent_vulnerabilities,
    scan_completion_transaction,
)

__all__ = [
    'get_db_config',
    'get_pool',
    'get_connection',
    'get_user_by_email',
    'create_user',
    'get_all_targets',
    'get_target_by_id',
    'get_target_by_url',
    'get_or_create_target',
    'update_target',
    'delete_target',
    'insert_scan_history',
    'get_scan_history_for_target',
    'insert_vulnerabilities',
    'get_vulnerabilities',
    'get_vulnerability_by_id',
    'get_vulnerabilities_by_target_url',
    'toggle_vulnerability_fixed',
    'get_dashboard_stats',
    'insert_report',
    'get_reports',
    'get_report_by_id',
    'get_recent_vulnerabilities',
    'scan_completion_transaction',
]
